#!/bin/bash
# author: Renato Mercurio, 2018
# descr: set pin in env without traces

echo "Enter PIN:"
read -s PIN

echo "Please enter PIN again to verify:"
read -s PIN2

if [ "$PIN" == "$PIN2" ]; then
  export PIN
  echo "Done: PIN set"
else
  echo "Failed: PIN's are not equal"
fi

